[colors.primary]
foreground = "#fffff8"
# foreground = "#cccbc8"
background = "#242424"

[colors.cursor]
text = "#000000"
# cursor = '#cccccc'
cursor = "#b9d177"
# cursor = "#9e9b9b" # slightly softened for better visibility

[colors.normal]
black = "#000000"
red = "#FA8072"
green = "#8daf79"
yellow = "#FAA166"
blue = "#799cd4"
magenta = "#F3F2CC"
cyan = "#d0c5a9"
white = "#e3dede"

[colors.selection]
text       = "#000000"
background = "#f0e68c"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#FAA166"
