unbind C-b
set -s escape-time 0
set-option -g prefix C-a

set-option -g default-terminal "screen-256color"

set -g default-terminal "alacritty" 
set-option -sa terminal-overrides ",alacritty*:Tc" 

set -g status-style "fg=#4e4e4e"
set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left "[#S] "
set -g status-right ""
setw -g mode-keys vi

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind Space copy-mode

set -g message-style "bg=#4e4e4e"
set -g mode-style "bg=#f0e68c,fg=black"
